name: unittest

on:
  # Run unit tests every-single-time on every-single-branch and allow custom runs
  pull_request:
  push:
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run unittests
        run: python -m unittest
